-- VHDL module instantiation generated by SCUBA Diamond_2.1_Production (100)
-- Module  Version: 5.4
-- Fri Jul 12 14:50:28 2013

-- parameterized module component declaration
component async_fifo_af_512x36_ecp3
    port (Data: in  std_logic_vector(35 downto 0); 
        WrClock: in  std_logic; RdClock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        RPReset: in  std_logic; Q: out  std_logic_vector(35 downto 0); 
        Empty: out  std_logic; Full: out  std_logic; 
        AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : async_fifo_af_512x36_ecp3
    port map (Data(35 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(35 downto 0)=>__, Empty=>__, 
        Full=>__, AlmostFull=>__);
