-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 3.5
-- Wed Jan 28 16:09:06 2015

-- parameterized module component declaration
component DLLl_in200M_out200M
    port (clki: in  std_logic; clkop: out  std_logic; 
        clkos: out  std_logic; lock: out  std_logic; 
        aluhold: in  std_logic);
end component;

-- parameterized module component instance
__ : DLLl_in200M_out200M
    port map (clki=>__, clkop=>__, clkos=>__, lock=>__, aluhold=>__);
