-- VHDL module instantiation generated by SCUBA Diamond_2.1_Production (100)
-- Module  Version: 5.3
-- Thu Jul 18 16:49:41 2013

-- parameterized module component declaration
component pll_in200_out125_62M5
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOS: out std_logic; 
        CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll_in200_out125_62M5
    port map (CLK=>__, CLKOP=>__, CLKOS=>__, CLKOK=>__, LOCK=>__);
