-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 5.6
-- Fri Aug 29 09:14:47 2014

-- parameterized module component declaration
component pll_in200_out160M_80M
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOK: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll_in200_out160M_80M
    port map (CLK=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);
