-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 5.6
-- Thu Nov 20 10:10:31 2014

-- parameterized module component declaration
component pll_in200_out200M_100M
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOS: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll_in200_out200M_100M
    port map (CLK=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
