-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 5.0
-- Wed Oct 08 11:23:07 2014

-- parameterized module component declaration
component sync_fifo_512x41_ecp3
    port (Data: in  std_logic_vector(40 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        Q: out  std_logic_vector(40 downto 0); Empty: out  std_logic; 
        Full: out  std_logic);
end component;

-- parameterized module component instance
__ : sync_fifo_512x41_ecp3
    port map (Data(40 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, 
        Reset=>__, Q(40 downto 0)=>__, Empty=>__, Full=>__);
