-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.6.0.83.4
-- Module  Version: 5.8
--/home/soft/lattice/diamond/3.6_x64/ispfpga/bin/lin64/scuba -w -n fifo_16kx16x64 -lang vhdl -synth lse -bus_exp 7 -bb -arch ep5c00 -type ebfifo -depth 8192 -width 18 -depth 8192 -rdata_width 72 -no_enable -pe -1 -pf -1 

-- Fri Nov 20 10:59:46 2015

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity fifo_16kx16x64 is
    port (
        Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(71 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic);
end fifo_16kx16x64;

architecture Structure of fifo_16kx16x64 is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal w_g2b_xor_cluster_2_1: std_logic;
    signal wcount_r1: std_logic;
    signal wcount_r0: std_logic;
    signal w_g2b_xor_cluster_3: std_logic;
    signal w_g2b_xor_cluster_2: std_logic;
    signal w_g2b_xor_cluster_1: std_logic;
    signal r_g2b_xor_cluster_2_1: std_logic;
    signal r_g2b_xor_cluster_2: std_logic;
    signal r_g2b_xor_cluster_1: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal w_gdata_3: std_logic;
    signal w_gdata_4: std_logic;
    signal w_gdata_5: std_logic;
    signal w_gdata_6: std_logic;
    signal w_gdata_7: std_logic;
    signal w_gdata_8: std_logic;
    signal w_gdata_9: std_logic;
    signal w_gdata_10: std_logic;
    signal w_gdata_11: std_logic;
    signal w_gdata_12: std_logic;
    signal wptr_0: std_logic;
    signal wptr_1: std_logic;
    signal wptr_2: std_logic;
    signal wptr_3: std_logic;
    signal wptr_4: std_logic;
    signal wptr_5: std_logic;
    signal wptr_6: std_logic;
    signal wptr_7: std_logic;
    signal wptr_8: std_logic;
    signal wptr_9: std_logic;
    signal wptr_10: std_logic;
    signal wptr_11: std_logic;
    signal wptr_12: std_logic;
    signal wptr_13: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal r_gdata_3: std_logic;
    signal r_gdata_4: std_logic;
    signal r_gdata_5: std_logic;
    signal r_gdata_6: std_logic;
    signal r_gdata_7: std_logic;
    signal r_gdata_8: std_logic;
    signal r_gdata_9: std_logic;
    signal r_gdata_10: std_logic;
    signal rptr_0: std_logic;
    signal rptr_1: std_logic;
    signal rptr_2: std_logic;
    signal rptr_3: std_logic;
    signal rptr_4: std_logic;
    signal rptr_5: std_logic;
    signal rptr_6: std_logic;
    signal rptr_7: std_logic;
    signal rptr_8: std_logic;
    signal rptr_11: std_logic;
    signal rptr_9: std_logic;
    signal rptr_10: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal w_gcount_4: std_logic;
    signal w_gcount_5: std_logic;
    signal w_gcount_6: std_logic;
    signal w_gcount_7: std_logic;
    signal w_gcount_8: std_logic;
    signal w_gcount_9: std_logic;
    signal w_gcount_10: std_logic;
    signal w_gcount_11: std_logic;
    signal w_gcount_12: std_logic;
    signal w_gcount_13: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal r_gcount_4: std_logic;
    signal r_gcount_5: std_logic;
    signal r_gcount_6: std_logic;
    signal r_gcount_7: std_logic;
    signal r_gcount_8: std_logic;
    signal r_gcount_9: std_logic;
    signal r_gcount_10: std_logic;
    signal r_gcount_11: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal w_gcount_r24: std_logic;
    signal w_gcount_r4: std_logic;
    signal w_gcount_r25: std_logic;
    signal w_gcount_r5: std_logic;
    signal w_gcount_r26: std_logic;
    signal w_gcount_r6: std_logic;
    signal w_gcount_r27: std_logic;
    signal w_gcount_r7: std_logic;
    signal w_gcount_r28: std_logic;
    signal w_gcount_r8: std_logic;
    signal w_gcount_r29: std_logic;
    signal w_gcount_r9: std_logic;
    signal w_gcount_r210: std_logic;
    signal w_gcount_r10: std_logic;
    signal w_gcount_r211: std_logic;
    signal w_gcount_r11: std_logic;
    signal w_gcount_r212: std_logic;
    signal w_gcount_r12: std_logic;
    signal w_gcount_r213: std_logic;
    signal w_gcount_r13: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal r_gcount_w24: std_logic;
    signal r_gcount_w4: std_logic;
    signal r_gcount_w25: std_logic;
    signal r_gcount_w5: std_logic;
    signal r_gcount_w26: std_logic;
    signal r_gcount_w6: std_logic;
    signal r_gcount_w27: std_logic;
    signal r_gcount_w7: std_logic;
    signal r_gcount_w28: std_logic;
    signal r_gcount_w8: std_logic;
    signal r_gcount_w29: std_logic;
    signal r_gcount_w9: std_logic;
    signal r_gcount_w210: std_logic;
    signal r_gcount_w10: std_logic;
    signal r_gcount_w211: std_logic;
    signal r_gcount_w11: std_logic;
    signal empty_i: std_logic;
    signal rRst: std_logic;
    signal full_i: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_gctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co0: std_logic;
    signal iwcount_4: std_logic;
    signal iwcount_5: std_logic;
    signal co1: std_logic;
    signal iwcount_6: std_logic;
    signal iwcount_7: std_logic;
    signal co2: std_logic;
    signal iwcount_8: std_logic;
    signal iwcount_9: std_logic;
    signal co3: std_logic;
    signal iwcount_10: std_logic;
    signal iwcount_11: std_logic;
    signal co4: std_logic;
    signal iwcount_12: std_logic;
    signal iwcount_13: std_logic;
    signal co6: std_logic;
    signal co5: std_logic;
    signal wcount_13: std_logic;
    signal scuba_vhi: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_gctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co0_1: std_logic;
    signal ircount_4: std_logic;
    signal ircount_5: std_logic;
    signal co1_1: std_logic;
    signal ircount_6: std_logic;
    signal ircount_7: std_logic;
    signal co2_1: std_logic;
    signal ircount_8: std_logic;
    signal ircount_9: std_logic;
    signal co3_1: std_logic;
    signal ircount_10: std_logic;
    signal ircount_11: std_logic;
    signal co5_1: std_logic;
    signal co4_1: std_logic;
    signal rcount_11: std_logic;
    signal mdout1_3_0: std_logic;
    signal mdout1_2_0: std_logic;
    signal mdout1_1_0: std_logic;
    signal mdout1_0_0: std_logic;
    signal mdout1_3_1: std_logic;
    signal mdout1_2_1: std_logic;
    signal mdout1_1_1: std_logic;
    signal mdout1_0_1: std_logic;
    signal mdout1_3_2: std_logic;
    signal mdout1_2_2: std_logic;
    signal mdout1_1_2: std_logic;
    signal mdout1_0_2: std_logic;
    signal mdout1_3_3: std_logic;
    signal mdout1_2_3: std_logic;
    signal mdout1_1_3: std_logic;
    signal mdout1_0_3: std_logic;
    signal mdout1_3_4: std_logic;
    signal mdout1_2_4: std_logic;
    signal mdout1_1_4: std_logic;
    signal mdout1_0_4: std_logic;
    signal mdout1_3_5: std_logic;
    signal mdout1_2_5: std_logic;
    signal mdout1_1_5: std_logic;
    signal mdout1_0_5: std_logic;
    signal mdout1_3_6: std_logic;
    signal mdout1_2_6: std_logic;
    signal mdout1_1_6: std_logic;
    signal mdout1_0_6: std_logic;
    signal mdout1_3_7: std_logic;
    signal mdout1_2_7: std_logic;
    signal mdout1_1_7: std_logic;
    signal mdout1_0_7: std_logic;
    signal mdout1_3_8: std_logic;
    signal mdout1_2_8: std_logic;
    signal mdout1_1_8: std_logic;
    signal mdout1_0_8: std_logic;
    signal mdout1_3_9: std_logic;
    signal mdout1_2_9: std_logic;
    signal mdout1_1_9: std_logic;
    signal mdout1_0_9: std_logic;
    signal mdout1_3_10: std_logic;
    signal mdout1_2_10: std_logic;
    signal mdout1_1_10: std_logic;
    signal mdout1_0_10: std_logic;
    signal mdout1_3_11: std_logic;
    signal mdout1_2_11: std_logic;
    signal mdout1_1_11: std_logic;
    signal mdout1_0_11: std_logic;
    signal mdout1_3_12: std_logic;
    signal mdout1_2_12: std_logic;
    signal mdout1_1_12: std_logic;
    signal mdout1_0_12: std_logic;
    signal mdout1_3_13: std_logic;
    signal mdout1_2_13: std_logic;
    signal mdout1_1_13: std_logic;
    signal mdout1_0_13: std_logic;
    signal mdout1_3_14: std_logic;
    signal mdout1_2_14: std_logic;
    signal mdout1_1_14: std_logic;
    signal mdout1_0_14: std_logic;
    signal mdout1_3_15: std_logic;
    signal mdout1_2_15: std_logic;
    signal mdout1_1_15: std_logic;
    signal mdout1_0_15: std_logic;
    signal mdout1_3_16: std_logic;
    signal mdout1_2_16: std_logic;
    signal mdout1_1_16: std_logic;
    signal mdout1_0_16: std_logic;
    signal mdout1_3_17: std_logic;
    signal mdout1_2_17: std_logic;
    signal mdout1_1_17: std_logic;
    signal mdout1_0_17: std_logic;
    signal mdout1_3_18: std_logic;
    signal mdout1_2_18: std_logic;
    signal mdout1_1_18: std_logic;
    signal mdout1_0_18: std_logic;
    signal mdout1_3_19: std_logic;
    signal mdout1_2_19: std_logic;
    signal mdout1_1_19: std_logic;
    signal mdout1_0_19: std_logic;
    signal mdout1_3_20: std_logic;
    signal mdout1_2_20: std_logic;
    signal mdout1_1_20: std_logic;
    signal mdout1_0_20: std_logic;
    signal mdout1_3_21: std_logic;
    signal mdout1_2_21: std_logic;
    signal mdout1_1_21: std_logic;
    signal mdout1_0_21: std_logic;
    signal mdout1_3_22: std_logic;
    signal mdout1_2_22: std_logic;
    signal mdout1_1_22: std_logic;
    signal mdout1_0_22: std_logic;
    signal mdout1_3_23: std_logic;
    signal mdout1_2_23: std_logic;
    signal mdout1_1_23: std_logic;
    signal mdout1_0_23: std_logic;
    signal mdout1_3_24: std_logic;
    signal mdout1_2_24: std_logic;
    signal mdout1_1_24: std_logic;
    signal mdout1_0_24: std_logic;
    signal mdout1_3_25: std_logic;
    signal mdout1_2_25: std_logic;
    signal mdout1_1_25: std_logic;
    signal mdout1_0_25: std_logic;
    signal mdout1_3_26: std_logic;
    signal mdout1_2_26: std_logic;
    signal mdout1_1_26: std_logic;
    signal mdout1_0_26: std_logic;
    signal mdout1_3_27: std_logic;
    signal mdout1_2_27: std_logic;
    signal mdout1_1_27: std_logic;
    signal mdout1_0_27: std_logic;
    signal mdout1_3_28: std_logic;
    signal mdout1_2_28: std_logic;
    signal mdout1_1_28: std_logic;
    signal mdout1_0_28: std_logic;
    signal mdout1_3_29: std_logic;
    signal mdout1_2_29: std_logic;
    signal mdout1_1_29: std_logic;
    signal mdout1_0_29: std_logic;
    signal mdout1_3_30: std_logic;
    signal mdout1_2_30: std_logic;
    signal mdout1_1_30: std_logic;
    signal mdout1_0_30: std_logic;
    signal mdout1_3_31: std_logic;
    signal mdout1_2_31: std_logic;
    signal mdout1_1_31: std_logic;
    signal mdout1_0_31: std_logic;
    signal mdout1_3_32: std_logic;
    signal mdout1_2_32: std_logic;
    signal mdout1_1_32: std_logic;
    signal mdout1_0_32: std_logic;
    signal mdout1_3_33: std_logic;
    signal mdout1_2_33: std_logic;
    signal mdout1_1_33: std_logic;
    signal mdout1_0_33: std_logic;
    signal mdout1_3_34: std_logic;
    signal mdout1_2_34: std_logic;
    signal mdout1_1_34: std_logic;
    signal mdout1_0_34: std_logic;
    signal mdout1_3_35: std_logic;
    signal mdout1_2_35: std_logic;
    signal mdout1_1_35: std_logic;
    signal mdout1_0_35: std_logic;
    signal mdout1_3_36: std_logic;
    signal mdout1_2_36: std_logic;
    signal mdout1_1_36: std_logic;
    signal mdout1_0_36: std_logic;
    signal mdout1_3_37: std_logic;
    signal mdout1_2_37: std_logic;
    signal mdout1_1_37: std_logic;
    signal mdout1_0_37: std_logic;
    signal mdout1_3_38: std_logic;
    signal mdout1_2_38: std_logic;
    signal mdout1_1_38: std_logic;
    signal mdout1_0_38: std_logic;
    signal mdout1_3_39: std_logic;
    signal mdout1_2_39: std_logic;
    signal mdout1_1_39: std_logic;
    signal mdout1_0_39: std_logic;
    signal mdout1_3_40: std_logic;
    signal mdout1_2_40: std_logic;
    signal mdout1_1_40: std_logic;
    signal mdout1_0_40: std_logic;
    signal mdout1_3_41: std_logic;
    signal mdout1_2_41: std_logic;
    signal mdout1_1_41: std_logic;
    signal mdout1_0_41: std_logic;
    signal mdout1_3_42: std_logic;
    signal mdout1_2_42: std_logic;
    signal mdout1_1_42: std_logic;
    signal mdout1_0_42: std_logic;
    signal mdout1_3_43: std_logic;
    signal mdout1_2_43: std_logic;
    signal mdout1_1_43: std_logic;
    signal mdout1_0_43: std_logic;
    signal mdout1_3_44: std_logic;
    signal mdout1_2_44: std_logic;
    signal mdout1_1_44: std_logic;
    signal mdout1_0_44: std_logic;
    signal mdout1_3_45: std_logic;
    signal mdout1_2_45: std_logic;
    signal mdout1_1_45: std_logic;
    signal mdout1_0_45: std_logic;
    signal mdout1_3_46: std_logic;
    signal mdout1_2_46: std_logic;
    signal mdout1_1_46: std_logic;
    signal mdout1_0_46: std_logic;
    signal mdout1_3_47: std_logic;
    signal mdout1_2_47: std_logic;
    signal mdout1_1_47: std_logic;
    signal mdout1_0_47: std_logic;
    signal mdout1_3_48: std_logic;
    signal mdout1_2_48: std_logic;
    signal mdout1_1_48: std_logic;
    signal mdout1_0_48: std_logic;
    signal mdout1_3_49: std_logic;
    signal mdout1_2_49: std_logic;
    signal mdout1_1_49: std_logic;
    signal mdout1_0_49: std_logic;
    signal mdout1_3_50: std_logic;
    signal mdout1_2_50: std_logic;
    signal mdout1_1_50: std_logic;
    signal mdout1_0_50: std_logic;
    signal mdout1_3_51: std_logic;
    signal mdout1_2_51: std_logic;
    signal mdout1_1_51: std_logic;
    signal mdout1_0_51: std_logic;
    signal mdout1_3_52: std_logic;
    signal mdout1_2_52: std_logic;
    signal mdout1_1_52: std_logic;
    signal mdout1_0_52: std_logic;
    signal mdout1_3_53: std_logic;
    signal mdout1_2_53: std_logic;
    signal mdout1_1_53: std_logic;
    signal mdout1_0_53: std_logic;
    signal mdout1_3_54: std_logic;
    signal mdout1_2_54: std_logic;
    signal mdout1_1_54: std_logic;
    signal mdout1_0_54: std_logic;
    signal mdout1_3_55: std_logic;
    signal mdout1_2_55: std_logic;
    signal mdout1_1_55: std_logic;
    signal mdout1_0_55: std_logic;
    signal mdout1_3_56: std_logic;
    signal mdout1_2_56: std_logic;
    signal mdout1_1_56: std_logic;
    signal mdout1_0_56: std_logic;
    signal mdout1_3_57: std_logic;
    signal mdout1_2_57: std_logic;
    signal mdout1_1_57: std_logic;
    signal mdout1_0_57: std_logic;
    signal mdout1_3_58: std_logic;
    signal mdout1_2_58: std_logic;
    signal mdout1_1_58: std_logic;
    signal mdout1_0_58: std_logic;
    signal mdout1_3_59: std_logic;
    signal mdout1_2_59: std_logic;
    signal mdout1_1_59: std_logic;
    signal mdout1_0_59: std_logic;
    signal mdout1_3_60: std_logic;
    signal mdout1_2_60: std_logic;
    signal mdout1_1_60: std_logic;
    signal mdout1_0_60: std_logic;
    signal mdout1_3_61: std_logic;
    signal mdout1_2_61: std_logic;
    signal mdout1_1_61: std_logic;
    signal mdout1_0_61: std_logic;
    signal mdout1_3_62: std_logic;
    signal mdout1_2_62: std_logic;
    signal mdout1_1_62: std_logic;
    signal mdout1_0_62: std_logic;
    signal mdout1_3_63: std_logic;
    signal mdout1_2_63: std_logic;
    signal mdout1_1_63: std_logic;
    signal mdout1_0_63: std_logic;
    signal mdout1_3_64: std_logic;
    signal mdout1_2_64: std_logic;
    signal mdout1_1_64: std_logic;
    signal mdout1_0_64: std_logic;
    signal mdout1_3_65: std_logic;
    signal mdout1_2_65: std_logic;
    signal mdout1_1_65: std_logic;
    signal mdout1_0_65: std_logic;
    signal mdout1_3_66: std_logic;
    signal mdout1_2_66: std_logic;
    signal mdout1_1_66: std_logic;
    signal mdout1_0_66: std_logic;
    signal mdout1_3_67: std_logic;
    signal mdout1_2_67: std_logic;
    signal mdout1_1_67: std_logic;
    signal mdout1_0_67: std_logic;
    signal mdout1_3_68: std_logic;
    signal mdout1_2_68: std_logic;
    signal mdout1_1_68: std_logic;
    signal mdout1_0_68: std_logic;
    signal mdout1_3_69: std_logic;
    signal mdout1_2_69: std_logic;
    signal mdout1_1_69: std_logic;
    signal mdout1_0_69: std_logic;
    signal mdout1_3_70: std_logic;
    signal mdout1_2_70: std_logic;
    signal mdout1_1_70: std_logic;
    signal mdout1_0_70: std_logic;
    signal rptr_10_ff: std_logic;
    signal rptr_9_ff: std_logic;
    signal mdout1_3_71: std_logic;
    signal mdout1_2_71: std_logic;
    signal mdout1_1_71: std_logic;
    signal mdout1_0_71: std_logic;
    signal rden_i: std_logic;
    signal cmp_ci: std_logic;
    signal wcount_r2: std_logic;
    signal wcount_r3: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_2: std_logic;
    signal wcount_r4: std_logic;
    signal wcount_r5: std_logic;
    signal rcount_2: std_logic;
    signal rcount_3: std_logic;
    signal co1_2: std_logic;
    signal wcount_r6: std_logic;
    signal wcount_r7: std_logic;
    signal rcount_4: std_logic;
    signal rcount_5: std_logic;
    signal co2_2: std_logic;
    signal wcount_r8: std_logic;
    signal wcount_r9: std_logic;
    signal rcount_6: std_logic;
    signal rcount_7: std_logic;
    signal co3_2: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r11: std_logic;
    signal rcount_8: std_logic;
    signal rcount_9: std_logic;
    signal co4_2: std_logic;
    signal wcount_r12: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_10: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal wren_i: std_logic;
    signal cmp_ci_1: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_3: std_logic;
    signal rcount_w0: std_logic;
    signal rcount_w1: std_logic;
    signal wcount_2: std_logic;
    signal wcount_3: std_logic;
    signal co1_3: std_logic;
    signal rcount_w2: std_logic;
    signal rcount_w3: std_logic;
    signal wcount_4: std_logic;
    signal wcount_5: std_logic;
    signal co2_3: std_logic;
    signal rcount_w4: std_logic;
    signal rcount_w5: std_logic;
    signal wcount_6: std_logic;
    signal wcount_7: std_logic;
    signal co3_3: std_logic;
    signal rcount_w6: std_logic;
    signal rcount_w7: std_logic;
    signal wcount_8: std_logic;
    signal wcount_9: std_logic;
    signal co4_3: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal rcount_w9: std_logic;
    signal wcount_10: std_logic;
    signal wcount_11: std_logic;
    signal co5_2: std_logic;
    signal rcount_w10: std_logic;
    signal full_cmp_clr: std_logic;
    signal wcount_12: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal full_d_c: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component AGEB2
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; GE: out  std_logic);
    end component;
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component CU2
        port (CI: in  std_logic; PC0: in  std_logic; PC1: in  std_logic; 
            CO: out  std_logic; NC0: out  std_logic; NC1: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3BX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1S3BX
        port (D: in  std_logic; CK: in  std_logic; PD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component FD1S3DX
        port (D: in  std_logic; CK: in  std_logic; CD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component MUX41
        port (D0: in  std_logic; D1: in  std_logic; D2: in  std_logic; 
            D3: in  std_logic; SD1: in  std_logic; SD2: in  std_logic; 
            Z: out  std_logic);
    end component;
    component OR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component XOR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component DP16KC
        generic (GSR : in String; WRITEMODE_B : in String; 
                WRITEMODE_A : in String; CSDECODE_B : in String; 
                CSDECODE_A : in String; REGMODE_B : in String; 
                REGMODE_A : in String; DATA_WIDTH_B : in Integer; 
                DATA_WIDTH_A : in Integer);
        port (DIA0: in  std_logic; DIA1: in  std_logic; 
            DIA2: in  std_logic; DIA3: in  std_logic; 
            DIA4: in  std_logic; DIA5: in  std_logic; 
            DIA6: in  std_logic; DIA7: in  std_logic; 
            DIA8: in  std_logic; DIA9: in  std_logic; 
            DIA10: in  std_logic; DIA11: in  std_logic; 
            DIA12: in  std_logic; DIA13: in  std_logic; 
            DIA14: in  std_logic; DIA15: in  std_logic; 
            DIA16: in  std_logic; DIA17: in  std_logic; 
            ADA0: in  std_logic; ADA1: in  std_logic; 
            ADA2: in  std_logic; ADA3: in  std_logic; 
            ADA4: in  std_logic; ADA5: in  std_logic; 
            ADA6: in  std_logic; ADA7: in  std_logic; 
            ADA8: in  std_logic; ADA9: in  std_logic; 
            ADA10: in  std_logic; ADA11: in  std_logic; 
            ADA12: in  std_logic; ADA13: in  std_logic; 
            CEA: in  std_logic; CLKA: in  std_logic; OCEA: in  std_logic; 
            WEA: in  std_logic; CSA0: in  std_logic; CSA1: in  std_logic; 
            CSA2: in  std_logic; RSTA: in  std_logic; 
            DIB0: in  std_logic; DIB1: in  std_logic; 
            DIB2: in  std_logic; DIB3: in  std_logic; 
            DIB4: in  std_logic; DIB5: in  std_logic; 
            DIB6: in  std_logic; DIB7: in  std_logic; 
            DIB8: in  std_logic; DIB9: in  std_logic; 
            DIB10: in  std_logic; DIB11: in  std_logic; 
            DIB12: in  std_logic; DIB13: in  std_logic; 
            DIB14: in  std_logic; DIB15: in  std_logic; 
            DIB16: in  std_logic; DIB17: in  std_logic; 
            ADB0: in  std_logic; ADB1: in  std_logic; 
            ADB2: in  std_logic; ADB3: in  std_logic; 
            ADB4: in  std_logic; ADB5: in  std_logic; 
            ADB6: in  std_logic; ADB7: in  std_logic; 
            ADB8: in  std_logic; ADB9: in  std_logic; 
            ADB10: in  std_logic; ADB11: in  std_logic; 
            ADB12: in  std_logic; ADB13: in  std_logic; 
            CEB: in  std_logic; CLKB: in  std_logic; OCEB: in  std_logic; 
            WEB: in  std_logic; CSB0: in  std_logic; CSB1: in  std_logic; 
            CSB2: in  std_logic; RSTB: in  std_logic; 
            DOA0: out  std_logic; DOA1: out  std_logic; 
            DOA2: out  std_logic; DOA3: out  std_logic; 
            DOA4: out  std_logic; DOA5: out  std_logic; 
            DOA6: out  std_logic; DOA7: out  std_logic; 
            DOA8: out  std_logic; DOA9: out  std_logic; 
            DOA10: out  std_logic; DOA11: out  std_logic; 
            DOA12: out  std_logic; DOA13: out  std_logic; 
            DOA14: out  std_logic; DOA15: out  std_logic; 
            DOA16: out  std_logic; DOA17: out  std_logic; 
            DOB0: out  std_logic; DOB1: out  std_logic; 
            DOB2: out  std_logic; DOB3: out  std_logic; 
            DOB4: out  std_logic; DOB5: out  std_logic; 
            DOB6: out  std_logic; DOB7: out  std_logic; 
            DOB8: out  std_logic; DOB9: out  std_logic; 
            DOB10: out  std_logic; DOB11: out  std_logic; 
            DOB12: out  std_logic; DOB13: out  std_logic; 
            DOB14: out  std_logic; DOB15: out  std_logic; 
            DOB16: out  std_logic; DOB17: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute RESETMODE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of pdp_ram_0_0_7 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_0_7 : label is "";
    attribute RESETMODE of pdp_ram_0_0_7 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_0_1_6 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_1_6 : label is "";
    attribute RESETMODE of pdp_ram_0_1_6 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_1_0_5 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_1_0_5 : label is "";
    attribute RESETMODE of pdp_ram_1_0_5 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_1_1_4 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_1_1_4 : label is "";
    attribute RESETMODE of pdp_ram_1_1_4 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_2_0_3 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_2_0_3 : label is "";
    attribute RESETMODE of pdp_ram_2_0_3 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_2_1_2 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_2_1_2 : label is "";
    attribute RESETMODE of pdp_ram_2_1_2 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_3_0_1 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_3_0_1 : label is "";
    attribute RESETMODE of pdp_ram_3_0_1 : label is "SYNC";
    attribute MEM_LPC_FILE of pdp_ram_3_1_0 : label is "fifo_16kx16x64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_3_1_0 : label is "";
    attribute RESETMODE of pdp_ram_3_1_0 : label is "SYNC";
    attribute GSR of FF_133 : label is "ENABLED";
    attribute GSR of FF_132 : label is "ENABLED";
    attribute GSR of FF_131 : label is "ENABLED";
    attribute GSR of FF_130 : label is "ENABLED";
    attribute GSR of FF_129 : label is "ENABLED";
    attribute GSR of FF_128 : label is "ENABLED";
    attribute GSR of FF_127 : label is "ENABLED";
    attribute GSR of FF_126 : label is "ENABLED";
    attribute GSR of FF_125 : label is "ENABLED";
    attribute GSR of FF_124 : label is "ENABLED";
    attribute GSR of FF_123 : label is "ENABLED";
    attribute GSR of FF_122 : label is "ENABLED";
    attribute GSR of FF_121 : label is "ENABLED";
    attribute GSR of FF_120 : label is "ENABLED";
    attribute GSR of FF_119 : label is "ENABLED";
    attribute GSR of FF_118 : label is "ENABLED";
    attribute GSR of FF_117 : label is "ENABLED";
    attribute GSR of FF_116 : label is "ENABLED";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    AND2_t26: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t25: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t24: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t23: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t22: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t21: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t20: XOR2
        port map (A=>wcount_3, B=>wcount_4, Z=>w_gdata_3);

    XOR2_t19: XOR2
        port map (A=>wcount_4, B=>wcount_5, Z=>w_gdata_4);

    XOR2_t18: XOR2
        port map (A=>wcount_5, B=>wcount_6, Z=>w_gdata_5);

    XOR2_t17: XOR2
        port map (A=>wcount_6, B=>wcount_7, Z=>w_gdata_6);

    XOR2_t16: XOR2
        port map (A=>wcount_7, B=>wcount_8, Z=>w_gdata_7);

    XOR2_t15: XOR2
        port map (A=>wcount_8, B=>wcount_9, Z=>w_gdata_8);

    XOR2_t14: XOR2
        port map (A=>wcount_9, B=>wcount_10, Z=>w_gdata_9);

    XOR2_t13: XOR2
        port map (A=>wcount_10, B=>wcount_11, Z=>w_gdata_10);

    XOR2_t12: XOR2
        port map (A=>wcount_11, B=>wcount_12, Z=>w_gdata_11);

    XOR2_t11: XOR2
        port map (A=>wcount_12, B=>wcount_13, Z=>w_gdata_12);

    XOR2_t10: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t9: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t8: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    XOR2_t7: XOR2
        port map (A=>rcount_3, B=>rcount_4, Z=>r_gdata_3);

    XOR2_t6: XOR2
        port map (A=>rcount_4, B=>rcount_5, Z=>r_gdata_4);

    XOR2_t5: XOR2
        port map (A=>rcount_5, B=>rcount_6, Z=>r_gdata_5);

    XOR2_t4: XOR2
        port map (A=>rcount_6, B=>rcount_7, Z=>r_gdata_6);

    XOR2_t3: XOR2
        port map (A=>rcount_7, B=>rcount_8, Z=>r_gdata_7);

    XOR2_t2: XOR2
        port map (A=>rcount_8, B=>rcount_9, Z=>r_gdata_8);

    XOR2_t1: XOR2
        port map (A=>rcount_9, B=>rcount_10, Z=>r_gdata_9);

    XOR2_t0: XOR2
        port map (A=>rcount_10, B=>rcount_11, Z=>r_gdata_10);

    LUT4_34: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r210, AD2=>w_gcount_r211, 
            AD1=>w_gcount_r212, AD0=>w_gcount_r213, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_33: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r26, AD2=>w_gcount_r27, 
            AD1=>w_gcount_r28, AD0=>w_gcount_r29, 
            DO0=>w_g2b_xor_cluster_1);

    LUT4_32: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r22, AD2=>w_gcount_r23, 
            AD1=>w_gcount_r24, AD0=>w_gcount_r25, 
            DO0=>w_g2b_xor_cluster_2);

    LUT4_31: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r212, AD2=>w_gcount_r213, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r12);

    LUT4_30: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r211, AD2=>w_gcount_r212, 
            AD1=>w_gcount_r213, AD0=>scuba_vlo, DO0=>wcount_r11);

    LUT4_29: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r29, AD2=>w_gcount_r210, 
            AD1=>w_gcount_r211, AD0=>wcount_r12, DO0=>wcount_r9);

    LUT4_28: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r28, AD2=>w_gcount_r29, 
            AD1=>w_gcount_r210, AD0=>wcount_r11, DO0=>wcount_r8);

    LUT4_27: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r27, AD2=>w_gcount_r28, 
            AD1=>w_gcount_r29, AD0=>w_g2b_xor_cluster_0, DO0=>wcount_r7);

    LUT4_26: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>wcount_r6);

    LUT4_25: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r25, AD0=>scuba_vlo, DO0=>wcount_r5);

    LUT4_24: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r24, AD0=>w_gcount_r25, DO0=>wcount_r4);

    LUT4_23: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r23, AD2=>w_gcount_r24, 
            AD1=>w_gcount_r25, AD0=>scuba_vlo, 
            DO0=>w_g2b_xor_cluster_2_1);

    LUT4_22: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2_1, AD0=>scuba_vlo, DO0=>wcount_r3);

    LUT4_21: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>wcount_r2);

    LUT4_20: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2, AD0=>w_gcount_r21, DO0=>wcount_r1);

    LUT4_19: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r20, AD2=>w_gcount_r21, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>w_g2b_xor_cluster_3);

    LUT4_18: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2, AD0=>w_g2b_xor_cluster_3, 
            DO0=>wcount_r0);

    LUT4_17: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w28, AD2=>r_gcount_w29, 
            AD1=>r_gcount_w210, AD0=>r_gcount_w211, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_16: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w24, AD2=>r_gcount_w25, 
            AD1=>r_gcount_w26, AD0=>r_gcount_w27, 
            DO0=>r_g2b_xor_cluster_1);

    LUT4_15: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w20, AD2=>r_gcount_w21, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, 
            DO0=>r_g2b_xor_cluster_2);

    LUT4_14: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w210, AD2=>r_gcount_w211, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w10);

    LUT4_13: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w29, AD2=>r_gcount_w210, 
            AD1=>r_gcount_w211, AD0=>scuba_vlo, DO0=>rcount_w9);

    LUT4_12: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w27, AD2=>r_gcount_w28, 
            AD1=>r_gcount_w29, AD0=>rcount_w10, DO0=>rcount_w7);

    LUT4_11: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w26, AD2=>r_gcount_w27, 
            AD1=>r_gcount_w28, AD0=>rcount_w9, DO0=>rcount_w6);

    LUT4_10: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w25, AD2=>r_gcount_w26, 
            AD1=>r_gcount_w27, AD0=>r_g2b_xor_cluster_0, DO0=>rcount_w5);

    LUT4_9: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>rcount_w4);

    LUT4_8: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, DO0=>rcount_w3);

    LUT4_7: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, DO0=>rcount_w2);

    LUT4_6: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w21, AD2=>r_gcount_w22, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, 
            DO0=>r_g2b_xor_cluster_2_1);

    LUT4_5: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2_1, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_4: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>rcount_w0);

    LUT4_3: ROM16X1A
        generic map (initval=> X"0410")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r213, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_2: ROM16X1A
        generic map (initval=> X"1004")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r213, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_1: ROM16X1A
        generic map (initval=> X"0140")
        port map (AD3=>wptr_13, AD2=>wcount_13, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_0: ROM16X1A
        generic map (initval=> X"4001")
        port map (AD3=>wptr_13, AD2=>wcount_13, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    pdp_ram_0_0_7: DP16KC
        generic map (CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(0), DIA1=>Data(1), DIA2=>Data(2), 
            DIA3=>Data(3), DIA4=>Data(4), DIA5=>Data(5), DIA6=>Data(6), 
            DIA7=>Data(7), DIA8=>Data(8), DIA9=>scuba_vlo, 
            DIA10=>scuba_vlo, DIA11=>scuba_vlo, DIA12=>scuba_vlo, 
            DIA13=>scuba_vlo, DIA14=>scuba_vlo, DIA15=>scuba_vlo, 
            DIA16=>scuba_vlo, DIA17=>scuba_vlo, ADA0=>scuba_vlo, 
            ADA1=>scuba_vlo, ADA2=>scuba_vlo, ADA3=>wptr_0, ADA4=>wptr_1, 
            ADA5=>wptr_2, ADA6=>wptr_3, ADA7=>wptr_4, ADA8=>wptr_5, 
            ADA9=>wptr_6, ADA10=>wptr_7, ADA11=>wptr_8, ADA12=>wptr_9, 
            ADA13=>wptr_10, CEA=>wren_i, CLKA=>WrClock, OCEA=>wren_i, 
            WEA=>scuba_vhi, CSA0=>wptr_11, CSA1=>wptr_12, 
            CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_0_0, 
            DOA1=>mdout1_0_1, DOA2=>mdout1_0_2, DOA3=>mdout1_0_3, 
            DOA4=>mdout1_0_4, DOA5=>mdout1_0_5, DOA6=>mdout1_0_6, 
            DOA7=>mdout1_0_7, DOA8=>mdout1_0_8, DOA9=>mdout1_0_18, 
            DOA10=>mdout1_0_19, DOA11=>mdout1_0_20, DOA12=>mdout1_0_21, 
            DOA13=>mdout1_0_22, DOA14=>mdout1_0_23, DOA15=>mdout1_0_24, 
            DOA16=>mdout1_0_25, DOA17=>mdout1_0_26, DOB0=>mdout1_0_36, 
            DOB1=>mdout1_0_37, DOB2=>mdout1_0_38, DOB3=>mdout1_0_39, 
            DOB4=>mdout1_0_40, DOB5=>mdout1_0_41, DOB6=>mdout1_0_42, 
            DOB7=>mdout1_0_43, DOB8=>mdout1_0_44, DOB9=>mdout1_0_54, 
            DOB10=>mdout1_0_55, DOB11=>mdout1_0_56, DOB12=>mdout1_0_57, 
            DOB13=>mdout1_0_58, DOB14=>mdout1_0_59, DOB15=>mdout1_0_60, 
            DOB16=>mdout1_0_61, DOB17=>mdout1_0_62);

    pdp_ram_0_1_6: DP16KC
        generic map (CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(9), DIA1=>Data(10), DIA2=>Data(11), 
            DIA3=>Data(12), DIA4=>Data(13), DIA5=>Data(14), 
            DIA6=>Data(15), DIA7=>Data(16), DIA8=>Data(17), 
            DIA9=>scuba_vlo, DIA10=>scuba_vlo, DIA11=>scuba_vlo, 
            DIA12=>scuba_vlo, DIA13=>scuba_vlo, DIA14=>scuba_vlo, 
            DIA15=>scuba_vlo, DIA16=>scuba_vlo, DIA17=>scuba_vlo, 
            ADA0=>scuba_vlo, ADA1=>scuba_vlo, ADA2=>scuba_vlo, 
            ADA3=>wptr_0, ADA4=>wptr_1, ADA5=>wptr_2, ADA6=>wptr_3, 
            ADA7=>wptr_4, ADA8=>wptr_5, ADA9=>wptr_6, ADA10=>wptr_7, 
            ADA11=>wptr_8, ADA12=>wptr_9, ADA13=>wptr_10, CEA=>wren_i, 
            CLKA=>WrClock, OCEA=>wren_i, WEA=>scuba_vhi, CSA0=>wptr_11, 
            CSA1=>wptr_12, CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_0_9, 
            DOA1=>mdout1_0_10, DOA2=>mdout1_0_11, DOA3=>mdout1_0_12, 
            DOA4=>mdout1_0_13, DOA5=>mdout1_0_14, DOA6=>mdout1_0_15, 
            DOA7=>mdout1_0_16, DOA8=>mdout1_0_17, DOA9=>mdout1_0_27, 
            DOA10=>mdout1_0_28, DOA11=>mdout1_0_29, DOA12=>mdout1_0_30, 
            DOA13=>mdout1_0_31, DOA14=>mdout1_0_32, DOA15=>mdout1_0_33, 
            DOA16=>mdout1_0_34, DOA17=>mdout1_0_35, DOB0=>mdout1_0_45, 
            DOB1=>mdout1_0_46, DOB2=>mdout1_0_47, DOB3=>mdout1_0_48, 
            DOB4=>mdout1_0_49, DOB5=>mdout1_0_50, DOB6=>mdout1_0_51, 
            DOB7=>mdout1_0_52, DOB8=>mdout1_0_53, DOB9=>mdout1_0_63, 
            DOB10=>mdout1_0_64, DOB11=>mdout1_0_65, DOB12=>mdout1_0_66, 
            DOB13=>mdout1_0_67, DOB14=>mdout1_0_68, DOB15=>mdout1_0_69, 
            DOB16=>mdout1_0_70, DOB17=>mdout1_0_71);

    pdp_ram_1_0_5: DP16KC
        generic map (CSDECODE_B=> "0b001", CSDECODE_A=> "0b001", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(0), DIA1=>Data(1), DIA2=>Data(2), 
            DIA3=>Data(3), DIA4=>Data(4), DIA5=>Data(5), DIA6=>Data(6), 
            DIA7=>Data(7), DIA8=>Data(8), DIA9=>scuba_vlo, 
            DIA10=>scuba_vlo, DIA11=>scuba_vlo, DIA12=>scuba_vlo, 
            DIA13=>scuba_vlo, DIA14=>scuba_vlo, DIA15=>scuba_vlo, 
            DIA16=>scuba_vlo, DIA17=>scuba_vlo, ADA0=>scuba_vlo, 
            ADA1=>scuba_vlo, ADA2=>scuba_vlo, ADA3=>wptr_0, ADA4=>wptr_1, 
            ADA5=>wptr_2, ADA6=>wptr_3, ADA7=>wptr_4, ADA8=>wptr_5, 
            ADA9=>wptr_6, ADA10=>wptr_7, ADA11=>wptr_8, ADA12=>wptr_9, 
            ADA13=>wptr_10, CEA=>wren_i, CLKA=>WrClock, OCEA=>wren_i, 
            WEA=>scuba_vhi, CSA0=>wptr_11, CSA1=>wptr_12, 
            CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_1_0, 
            DOA1=>mdout1_1_1, DOA2=>mdout1_1_2, DOA3=>mdout1_1_3, 
            DOA4=>mdout1_1_4, DOA5=>mdout1_1_5, DOA6=>mdout1_1_6, 
            DOA7=>mdout1_1_7, DOA8=>mdout1_1_8, DOA9=>mdout1_1_18, 
            DOA10=>mdout1_1_19, DOA11=>mdout1_1_20, DOA12=>mdout1_1_21, 
            DOA13=>mdout1_1_22, DOA14=>mdout1_1_23, DOA15=>mdout1_1_24, 
            DOA16=>mdout1_1_25, DOA17=>mdout1_1_26, DOB0=>mdout1_1_36, 
            DOB1=>mdout1_1_37, DOB2=>mdout1_1_38, DOB3=>mdout1_1_39, 
            DOB4=>mdout1_1_40, DOB5=>mdout1_1_41, DOB6=>mdout1_1_42, 
            DOB7=>mdout1_1_43, DOB8=>mdout1_1_44, DOB9=>mdout1_1_54, 
            DOB10=>mdout1_1_55, DOB11=>mdout1_1_56, DOB12=>mdout1_1_57, 
            DOB13=>mdout1_1_58, DOB14=>mdout1_1_59, DOB15=>mdout1_1_60, 
            DOB16=>mdout1_1_61, DOB17=>mdout1_1_62);

    pdp_ram_1_1_4: DP16KC
        generic map (CSDECODE_B=> "0b001", CSDECODE_A=> "0b001", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(9), DIA1=>Data(10), DIA2=>Data(11), 
            DIA3=>Data(12), DIA4=>Data(13), DIA5=>Data(14), 
            DIA6=>Data(15), DIA7=>Data(16), DIA8=>Data(17), 
            DIA9=>scuba_vlo, DIA10=>scuba_vlo, DIA11=>scuba_vlo, 
            DIA12=>scuba_vlo, DIA13=>scuba_vlo, DIA14=>scuba_vlo, 
            DIA15=>scuba_vlo, DIA16=>scuba_vlo, DIA17=>scuba_vlo, 
            ADA0=>scuba_vlo, ADA1=>scuba_vlo, ADA2=>scuba_vlo, 
            ADA3=>wptr_0, ADA4=>wptr_1, ADA5=>wptr_2, ADA6=>wptr_3, 
            ADA7=>wptr_4, ADA8=>wptr_5, ADA9=>wptr_6, ADA10=>wptr_7, 
            ADA11=>wptr_8, ADA12=>wptr_9, ADA13=>wptr_10, CEA=>wren_i, 
            CLKA=>WrClock, OCEA=>wren_i, WEA=>scuba_vhi, CSA0=>wptr_11, 
            CSA1=>wptr_12, CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_1_9, 
            DOA1=>mdout1_1_10, DOA2=>mdout1_1_11, DOA3=>mdout1_1_12, 
            DOA4=>mdout1_1_13, DOA5=>mdout1_1_14, DOA6=>mdout1_1_15, 
            DOA7=>mdout1_1_16, DOA8=>mdout1_1_17, DOA9=>mdout1_1_27, 
            DOA10=>mdout1_1_28, DOA11=>mdout1_1_29, DOA12=>mdout1_1_30, 
            DOA13=>mdout1_1_31, DOA14=>mdout1_1_32, DOA15=>mdout1_1_33, 
            DOA16=>mdout1_1_34, DOA17=>mdout1_1_35, DOB0=>mdout1_1_45, 
            DOB1=>mdout1_1_46, DOB2=>mdout1_1_47, DOB3=>mdout1_1_48, 
            DOB4=>mdout1_1_49, DOB5=>mdout1_1_50, DOB6=>mdout1_1_51, 
            DOB7=>mdout1_1_52, DOB8=>mdout1_1_53, DOB9=>mdout1_1_63, 
            DOB10=>mdout1_1_64, DOB11=>mdout1_1_65, DOB12=>mdout1_1_66, 
            DOB13=>mdout1_1_67, DOB14=>mdout1_1_68, DOB15=>mdout1_1_69, 
            DOB16=>mdout1_1_70, DOB17=>mdout1_1_71);

    pdp_ram_2_0_3: DP16KC
        generic map (CSDECODE_B=> "0b010", CSDECODE_A=> "0b010", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(0), DIA1=>Data(1), DIA2=>Data(2), 
            DIA3=>Data(3), DIA4=>Data(4), DIA5=>Data(5), DIA6=>Data(6), 
            DIA7=>Data(7), DIA8=>Data(8), DIA9=>scuba_vlo, 
            DIA10=>scuba_vlo, DIA11=>scuba_vlo, DIA12=>scuba_vlo, 
            DIA13=>scuba_vlo, DIA14=>scuba_vlo, DIA15=>scuba_vlo, 
            DIA16=>scuba_vlo, DIA17=>scuba_vlo, ADA0=>scuba_vlo, 
            ADA1=>scuba_vlo, ADA2=>scuba_vlo, ADA3=>wptr_0, ADA4=>wptr_1, 
            ADA5=>wptr_2, ADA6=>wptr_3, ADA7=>wptr_4, ADA8=>wptr_5, 
            ADA9=>wptr_6, ADA10=>wptr_7, ADA11=>wptr_8, ADA12=>wptr_9, 
            ADA13=>wptr_10, CEA=>wren_i, CLKA=>WrClock, OCEA=>wren_i, 
            WEA=>scuba_vhi, CSA0=>wptr_11, CSA1=>wptr_12, 
            CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_2_0, 
            DOA1=>mdout1_2_1, DOA2=>mdout1_2_2, DOA3=>mdout1_2_3, 
            DOA4=>mdout1_2_4, DOA5=>mdout1_2_5, DOA6=>mdout1_2_6, 
            DOA7=>mdout1_2_7, DOA8=>mdout1_2_8, DOA9=>mdout1_2_18, 
            DOA10=>mdout1_2_19, DOA11=>mdout1_2_20, DOA12=>mdout1_2_21, 
            DOA13=>mdout1_2_22, DOA14=>mdout1_2_23, DOA15=>mdout1_2_24, 
            DOA16=>mdout1_2_25, DOA17=>mdout1_2_26, DOB0=>mdout1_2_36, 
            DOB1=>mdout1_2_37, DOB2=>mdout1_2_38, DOB3=>mdout1_2_39, 
            DOB4=>mdout1_2_40, DOB5=>mdout1_2_41, DOB6=>mdout1_2_42, 
            DOB7=>mdout1_2_43, DOB8=>mdout1_2_44, DOB9=>mdout1_2_54, 
            DOB10=>mdout1_2_55, DOB11=>mdout1_2_56, DOB12=>mdout1_2_57, 
            DOB13=>mdout1_2_58, DOB14=>mdout1_2_59, DOB15=>mdout1_2_60, 
            DOB16=>mdout1_2_61, DOB17=>mdout1_2_62);

    pdp_ram_2_1_2: DP16KC
        generic map (CSDECODE_B=> "0b010", CSDECODE_A=> "0b010", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(9), DIA1=>Data(10), DIA2=>Data(11), 
            DIA3=>Data(12), DIA4=>Data(13), DIA5=>Data(14), 
            DIA6=>Data(15), DIA7=>Data(16), DIA8=>Data(17), 
            DIA9=>scuba_vlo, DIA10=>scuba_vlo, DIA11=>scuba_vlo, 
            DIA12=>scuba_vlo, DIA13=>scuba_vlo, DIA14=>scuba_vlo, 
            DIA15=>scuba_vlo, DIA16=>scuba_vlo, DIA17=>scuba_vlo, 
            ADA0=>scuba_vlo, ADA1=>scuba_vlo, ADA2=>scuba_vlo, 
            ADA3=>wptr_0, ADA4=>wptr_1, ADA5=>wptr_2, ADA6=>wptr_3, 
            ADA7=>wptr_4, ADA8=>wptr_5, ADA9=>wptr_6, ADA10=>wptr_7, 
            ADA11=>wptr_8, ADA12=>wptr_9, ADA13=>wptr_10, CEA=>wren_i, 
            CLKA=>WrClock, OCEA=>wren_i, WEA=>scuba_vhi, CSA0=>wptr_11, 
            CSA1=>wptr_12, CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_2_9, 
            DOA1=>mdout1_2_10, DOA2=>mdout1_2_11, DOA3=>mdout1_2_12, 
            DOA4=>mdout1_2_13, DOA5=>mdout1_2_14, DOA6=>mdout1_2_15, 
            DOA7=>mdout1_2_16, DOA8=>mdout1_2_17, DOA9=>mdout1_2_27, 
            DOA10=>mdout1_2_28, DOA11=>mdout1_2_29, DOA12=>mdout1_2_30, 
            DOA13=>mdout1_2_31, DOA14=>mdout1_2_32, DOA15=>mdout1_2_33, 
            DOA16=>mdout1_2_34, DOA17=>mdout1_2_35, DOB0=>mdout1_2_45, 
            DOB1=>mdout1_2_46, DOB2=>mdout1_2_47, DOB3=>mdout1_2_48, 
            DOB4=>mdout1_2_49, DOB5=>mdout1_2_50, DOB6=>mdout1_2_51, 
            DOB7=>mdout1_2_52, DOB8=>mdout1_2_53, DOB9=>mdout1_2_63, 
            DOB10=>mdout1_2_64, DOB11=>mdout1_2_65, DOB12=>mdout1_2_66, 
            DOB13=>mdout1_2_67, DOB14=>mdout1_2_68, DOB15=>mdout1_2_69, 
            DOB16=>mdout1_2_70, DOB17=>mdout1_2_71);

    pdp_ram_3_0_1: DP16KC
        generic map (CSDECODE_B=> "0b011", CSDECODE_A=> "0b011", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(0), DIA1=>Data(1), DIA2=>Data(2), 
            DIA3=>Data(3), DIA4=>Data(4), DIA5=>Data(5), DIA6=>Data(6), 
            DIA7=>Data(7), DIA8=>Data(8), DIA9=>scuba_vlo, 
            DIA10=>scuba_vlo, DIA11=>scuba_vlo, DIA12=>scuba_vlo, 
            DIA13=>scuba_vlo, DIA14=>scuba_vlo, DIA15=>scuba_vlo, 
            DIA16=>scuba_vlo, DIA17=>scuba_vlo, ADA0=>scuba_vlo, 
            ADA1=>scuba_vlo, ADA2=>scuba_vlo, ADA3=>wptr_0, ADA4=>wptr_1, 
            ADA5=>wptr_2, ADA6=>wptr_3, ADA7=>wptr_4, ADA8=>wptr_5, 
            ADA9=>wptr_6, ADA10=>wptr_7, ADA11=>wptr_8, ADA12=>wptr_9, 
            ADA13=>wptr_10, CEA=>wren_i, CLKA=>WrClock, OCEA=>wren_i, 
            WEA=>scuba_vhi, CSA0=>wptr_11, CSA1=>wptr_12, 
            CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_3_0, 
            DOA1=>mdout1_3_1, DOA2=>mdout1_3_2, DOA3=>mdout1_3_3, 
            DOA4=>mdout1_3_4, DOA5=>mdout1_3_5, DOA6=>mdout1_3_6, 
            DOA7=>mdout1_3_7, DOA8=>mdout1_3_8, DOA9=>mdout1_3_18, 
            DOA10=>mdout1_3_19, DOA11=>mdout1_3_20, DOA12=>mdout1_3_21, 
            DOA13=>mdout1_3_22, DOA14=>mdout1_3_23, DOA15=>mdout1_3_24, 
            DOA16=>mdout1_3_25, DOA17=>mdout1_3_26, DOB0=>mdout1_3_36, 
            DOB1=>mdout1_3_37, DOB2=>mdout1_3_38, DOB3=>mdout1_3_39, 
            DOB4=>mdout1_3_40, DOB5=>mdout1_3_41, DOB6=>mdout1_3_42, 
            DOB7=>mdout1_3_43, DOB8=>mdout1_3_44, DOB9=>mdout1_3_54, 
            DOB10=>mdout1_3_55, DOB11=>mdout1_3_56, DOB12=>mdout1_3_57, 
            DOB13=>mdout1_3_58, DOB14=>mdout1_3_59, DOB15=>mdout1_3_60, 
            DOB16=>mdout1_3_61, DOB17=>mdout1_3_62);

    pdp_ram_3_1_0: DP16KC
        generic map (CSDECODE_B=> "0b011", CSDECODE_A=> "0b011", 
        WRITEMODE_B=> "NORMAL", WRITEMODE_A=> "NORMAL", GSR=> "DISABLED", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  36, 
        DATA_WIDTH_A=>  9)
        port map (DIA0=>Data(9), DIA1=>Data(10), DIA2=>Data(11), 
            DIA3=>Data(12), DIA4=>Data(13), DIA5=>Data(14), 
            DIA6=>Data(15), DIA7=>Data(16), DIA8=>Data(17), 
            DIA9=>scuba_vlo, DIA10=>scuba_vlo, DIA11=>scuba_vlo, 
            DIA12=>scuba_vlo, DIA13=>scuba_vlo, DIA14=>scuba_vlo, 
            DIA15=>scuba_vlo, DIA16=>scuba_vlo, DIA17=>scuba_vlo, 
            ADA0=>scuba_vlo, ADA1=>scuba_vlo, ADA2=>scuba_vlo, 
            ADA3=>wptr_0, ADA4=>wptr_1, ADA5=>wptr_2, ADA6=>wptr_3, 
            ADA7=>wptr_4, ADA8=>wptr_5, ADA9=>wptr_6, ADA10=>wptr_7, 
            ADA11=>wptr_8, ADA12=>wptr_9, ADA13=>wptr_10, CEA=>wren_i, 
            CLKA=>WrClock, OCEA=>wren_i, WEA=>scuba_vhi, CSA0=>wptr_11, 
            CSA1=>wptr_12, CSA2=>scuba_vlo, RSTA=>Reset, DIB0=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB2=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB5=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB8=>scuba_vlo, DIB9=>scuba_vlo, 
            DIB10=>scuba_vlo, DIB11=>scuba_vlo, DIB12=>scuba_vlo, 
            DIB13=>scuba_vlo, DIB14=>scuba_vlo, DIB15=>scuba_vlo, 
            DIB16=>scuba_vlo, DIB17=>scuba_vlo, ADB0=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB2=>scuba_vlo, ADB3=>scuba_vlo, 
            ADB4=>scuba_vlo, ADB5=>rptr_0, ADB6=>rptr_1, ADB7=>rptr_2, 
            ADB8=>rptr_3, ADB9=>rptr_4, ADB10=>rptr_5, ADB11=>rptr_6, 
            ADB12=>rptr_7, ADB13=>rptr_8, CEB=>rden_i, CLKB=>RdClock, 
            OCEB=>rden_i, WEB=>scuba_vlo, CSB0=>rptr_9, CSB1=>rptr_10, 
            CSB2=>scuba_vlo, RSTB=>Reset, DOA0=>mdout1_3_9, 
            DOA1=>mdout1_3_10, DOA2=>mdout1_3_11, DOA3=>mdout1_3_12, 
            DOA4=>mdout1_3_13, DOA5=>mdout1_3_14, DOA6=>mdout1_3_15, 
            DOA7=>mdout1_3_16, DOA8=>mdout1_3_17, DOA9=>mdout1_3_27, 
            DOA10=>mdout1_3_28, DOA11=>mdout1_3_29, DOA12=>mdout1_3_30, 
            DOA13=>mdout1_3_31, DOA14=>mdout1_3_32, DOA15=>mdout1_3_33, 
            DOA16=>mdout1_3_34, DOA17=>mdout1_3_35, DOB0=>mdout1_3_45, 
            DOB1=>mdout1_3_46, DOB2=>mdout1_3_47, DOB3=>mdout1_3_48, 
            DOB4=>mdout1_3_49, DOB5=>mdout1_3_50, DOB6=>mdout1_3_51, 
            DOB7=>mdout1_3_52, DOB8=>mdout1_3_53, DOB9=>mdout1_3_63, 
            DOB10=>mdout1_3_64, DOB11=>mdout1_3_65, DOB12=>mdout1_3_66, 
            DOB13=>mdout1_3_67, DOB14=>mdout1_3_68, DOB15=>mdout1_3_69, 
            DOB16=>mdout1_3_70, DOB17=>mdout1_3_71);

    FF_133: FD1P3BX
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_132: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_131: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_130: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_129: FD1P3DX
        port map (D=>iwcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_4);

    FF_128: FD1P3DX
        port map (D=>iwcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_5);

    FF_127: FD1P3DX
        port map (D=>iwcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_6);

    FF_126: FD1P3DX
        port map (D=>iwcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_7);

    FF_125: FD1P3DX
        port map (D=>iwcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_8);

    FF_124: FD1P3DX
        port map (D=>iwcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_9);

    FF_123: FD1P3DX
        port map (D=>iwcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_10);

    FF_122: FD1P3DX
        port map (D=>iwcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_11);

    FF_121: FD1P3DX
        port map (D=>iwcount_12, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_12);

    FF_120: FD1P3DX
        port map (D=>iwcount_13, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_13);

    FF_119: FD1P3DX
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_118: FD1P3DX
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_117: FD1P3DX
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_116: FD1P3DX
        port map (D=>w_gdata_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_115: FD1P3DX
        port map (D=>w_gdata_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_4);

    FF_114: FD1P3DX
        port map (D=>w_gdata_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_5);

    FF_113: FD1P3DX
        port map (D=>w_gdata_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_6);

    FF_112: FD1P3DX
        port map (D=>w_gdata_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_7);

    FF_111: FD1P3DX
        port map (D=>w_gdata_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_8);

    FF_110: FD1P3DX
        port map (D=>w_gdata_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_9);

    FF_109: FD1P3DX
        port map (D=>w_gdata_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_10);

    FF_108: FD1P3DX
        port map (D=>w_gdata_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_11);

    FF_107: FD1P3DX
        port map (D=>w_gdata_12, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_12);

    FF_106: FD1P3DX
        port map (D=>wcount_13, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_13);

    FF_105: FD1P3DX
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_104: FD1P3DX
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_103: FD1P3DX
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_102: FD1P3DX
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_101: FD1P3DX
        port map (D=>wcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_4);

    FF_100: FD1P3DX
        port map (D=>wcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_5);

    FF_99: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_6);

    FF_98: FD1P3DX
        port map (D=>wcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_7);

    FF_97: FD1P3DX
        port map (D=>wcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_8);

    FF_96: FD1P3DX
        port map (D=>wcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_9);

    FF_95: FD1P3DX
        port map (D=>wcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_10);

    FF_94: FD1P3DX
        port map (D=>wcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_11);

    FF_93: FD1P3DX
        port map (D=>wcount_12, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_12);

    FF_92: FD1P3DX
        port map (D=>wcount_13, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_13);

    FF_91: FD1P3BX
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_90: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_89: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_88: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_87: FD1P3DX
        port map (D=>ircount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_4);

    FF_86: FD1P3DX
        port map (D=>ircount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_5);

    FF_85: FD1P3DX
        port map (D=>ircount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_6);

    FF_84: FD1P3DX
        port map (D=>ircount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_7);

    FF_83: FD1P3DX
        port map (D=>ircount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_8);

    FF_82: FD1P3DX
        port map (D=>ircount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_9);

    FF_81: FD1P3DX
        port map (D=>ircount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_10);

    FF_80: FD1P3DX
        port map (D=>ircount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_11);

    FF_79: FD1P3DX
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_78: FD1P3DX
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_77: FD1P3DX
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_76: FD1P3DX
        port map (D=>r_gdata_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_75: FD1P3DX
        port map (D=>r_gdata_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_4);

    FF_74: FD1P3DX
        port map (D=>r_gdata_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_5);

    FF_73: FD1P3DX
        port map (D=>r_gdata_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_6);

    FF_72: FD1P3DX
        port map (D=>r_gdata_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_7);

    FF_71: FD1P3DX
        port map (D=>r_gdata_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_8);

    FF_70: FD1P3DX
        port map (D=>r_gdata_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_9);

    FF_69: FD1P3DX
        port map (D=>r_gdata_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_10);

    FF_68: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_11);

    FF_67: FD1P3DX
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_66: FD1P3DX
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_65: FD1P3DX
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_64: FD1P3DX
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_63: FD1P3DX
        port map (D=>rcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_4);

    FF_62: FD1P3DX
        port map (D=>rcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_5);

    FF_61: FD1P3DX
        port map (D=>rcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_6);

    FF_60: FD1P3DX
        port map (D=>rcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_7);

    FF_59: FD1P3DX
        port map (D=>rcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_8);

    FF_58: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_9);

    FF_57: FD1P3DX
        port map (D=>rcount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_10);

    FF_56: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_11);

    FF_55: FD1P3DX
        port map (D=>rptr_9, SP=>rden_i, CK=>RdClock, CD=>scuba_vlo, 
            Q=>rptr_9_ff);

    FF_54: FD1P3DX
        port map (D=>rptr_10, SP=>rden_i, CK=>RdClock, CD=>scuba_vlo, 
            Q=>rptr_10_ff);

    FF_53: FD1S3DX
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_52: FD1S3DX
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_51: FD1S3DX
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_50: FD1S3DX
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_49: FD1S3DX
        port map (D=>w_gcount_4, CK=>RdClock, CD=>Reset, Q=>w_gcount_r4);

    FF_48: FD1S3DX
        port map (D=>w_gcount_5, CK=>RdClock, CD=>Reset, Q=>w_gcount_r5);

    FF_47: FD1S3DX
        port map (D=>w_gcount_6, CK=>RdClock, CD=>Reset, Q=>w_gcount_r6);

    FF_46: FD1S3DX
        port map (D=>w_gcount_7, CK=>RdClock, CD=>Reset, Q=>w_gcount_r7);

    FF_45: FD1S3DX
        port map (D=>w_gcount_8, CK=>RdClock, CD=>Reset, Q=>w_gcount_r8);

    FF_44: FD1S3DX
        port map (D=>w_gcount_9, CK=>RdClock, CD=>Reset, Q=>w_gcount_r9);

    FF_43: FD1S3DX
        port map (D=>w_gcount_10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r10);

    FF_42: FD1S3DX
        port map (D=>w_gcount_11, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r11);

    FF_41: FD1S3DX
        port map (D=>w_gcount_12, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r12);

    FF_40: FD1S3DX
        port map (D=>w_gcount_13, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r13);

    FF_39: FD1S3DX
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_38: FD1S3DX
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_37: FD1S3DX
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_36: FD1S3DX
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_35: FD1S3DX
        port map (D=>r_gcount_4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w4);

    FF_34: FD1S3DX
        port map (D=>r_gcount_5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w5);

    FF_33: FD1S3DX
        port map (D=>r_gcount_6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w6);

    FF_32: FD1S3DX
        port map (D=>r_gcount_7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w7);

    FF_31: FD1S3DX
        port map (D=>r_gcount_8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w8);

    FF_30: FD1S3DX
        port map (D=>r_gcount_9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w9);

    FF_29: FD1S3DX
        port map (D=>r_gcount_10, CK=>WrClock, CD=>rRst, Q=>r_gcount_w10);

    FF_28: FD1S3DX
        port map (D=>r_gcount_11, CK=>WrClock, CD=>rRst, Q=>r_gcount_w11);

    FF_27: FD1S3DX
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_26: FD1S3DX
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_25: FD1S3DX
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_24: FD1S3DX
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_23: FD1S3DX
        port map (D=>w_gcount_r4, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r24);

    FF_22: FD1S3DX
        port map (D=>w_gcount_r5, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r25);

    FF_21: FD1S3DX
        port map (D=>w_gcount_r6, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r26);

    FF_20: FD1S3DX
        port map (D=>w_gcount_r7, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r27);

    FF_19: FD1S3DX
        port map (D=>w_gcount_r8, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r28);

    FF_18: FD1S3DX
        port map (D=>w_gcount_r9, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r29);

    FF_17: FD1S3DX
        port map (D=>w_gcount_r10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r210);

    FF_16: FD1S3DX
        port map (D=>w_gcount_r11, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r211);

    FF_15: FD1S3DX
        port map (D=>w_gcount_r12, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r212);

    FF_14: FD1S3DX
        port map (D=>w_gcount_r13, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r213);

    FF_13: FD1S3DX
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_12: FD1S3DX
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_11: FD1S3DX
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_10: FD1S3DX
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_9: FD1S3DX
        port map (D=>r_gcount_w4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w24);

    FF_8: FD1S3DX
        port map (D=>r_gcount_w5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w25);

    FF_7: FD1S3DX
        port map (D=>r_gcount_w6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w26);

    FF_6: FD1S3DX
        port map (D=>r_gcount_w7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w27);

    FF_5: FD1S3DX
        port map (D=>r_gcount_w8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w28);

    FF_4: FD1S3DX
        port map (D=>r_gcount_w9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w29);

    FF_3: FD1S3DX
        port map (D=>r_gcount_w10, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w210);

    FF_2: FD1S3DX
        port map (D=>r_gcount_w11, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w211);

    FF_1: FD1S3BX
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_0: FD1S3DX
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    w_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>w_gctr_ci, S0=>open, 
            S1=>open);

    w_gctr_0: CU2
        port map (CI=>w_gctr_ci, PC0=>wcount_0, PC1=>wcount_1, CO=>co0, 
            NC0=>iwcount_0, NC1=>iwcount_1);

    w_gctr_1: CU2
        port map (CI=>co0, PC0=>wcount_2, PC1=>wcount_3, CO=>co1, 
            NC0=>iwcount_2, NC1=>iwcount_3);

    w_gctr_2: CU2
        port map (CI=>co1, PC0=>wcount_4, PC1=>wcount_5, CO=>co2, 
            NC0=>iwcount_4, NC1=>iwcount_5);

    w_gctr_3: CU2
        port map (CI=>co2, PC0=>wcount_6, PC1=>wcount_7, CO=>co3, 
            NC0=>iwcount_6, NC1=>iwcount_7);

    w_gctr_4: CU2
        port map (CI=>co3, PC0=>wcount_8, PC1=>wcount_9, CO=>co4, 
            NC0=>iwcount_8, NC1=>iwcount_9);

    w_gctr_5: CU2
        port map (CI=>co4, PC0=>wcount_10, PC1=>wcount_11, CO=>co5, 
            NC0=>iwcount_10, NC1=>iwcount_11);

    w_gctr_6: CU2
        port map (CI=>co5, PC0=>wcount_12, PC1=>wcount_13, CO=>co6, 
            NC0=>iwcount_12, NC1=>iwcount_13);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    r_gctr_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>r_gctr_ci, S0=>open, 
            S1=>open);

    r_gctr_0: CU2
        port map (CI=>r_gctr_ci, PC0=>rcount_0, PC1=>rcount_1, CO=>co0_1, 
            NC0=>ircount_0, NC1=>ircount_1);

    r_gctr_1: CU2
        port map (CI=>co0_1, PC0=>rcount_2, PC1=>rcount_3, CO=>co1_1, 
            NC0=>ircount_2, NC1=>ircount_3);

    r_gctr_2: CU2
        port map (CI=>co1_1, PC0=>rcount_4, PC1=>rcount_5, CO=>co2_1, 
            NC0=>ircount_4, NC1=>ircount_5);

    r_gctr_3: CU2
        port map (CI=>co2_1, PC0=>rcount_6, PC1=>rcount_7, CO=>co3_1, 
            NC0=>ircount_6, NC1=>ircount_7);

    r_gctr_4: CU2
        port map (CI=>co3_1, PC0=>rcount_8, PC1=>rcount_9, CO=>co4_1, 
            NC0=>ircount_8, NC1=>ircount_9);

    r_gctr_5: CU2
        port map (CI=>co4_1, PC0=>rcount_10, PC1=>rcount_11, CO=>co5_1, 
            NC0=>ircount_10, NC1=>ircount_11);

    mux_71: MUX41
        port map (D0=>mdout1_0_0, D1=>mdout1_1_0, D2=>mdout1_2_0, 
            D3=>mdout1_3_0, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(0));

    mux_70: MUX41
        port map (D0=>mdout1_0_1, D1=>mdout1_1_1, D2=>mdout1_2_1, 
            D3=>mdout1_3_1, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(1));

    mux_69: MUX41
        port map (D0=>mdout1_0_2, D1=>mdout1_1_2, D2=>mdout1_2_2, 
            D3=>mdout1_3_2, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(2));

    mux_68: MUX41
        port map (D0=>mdout1_0_3, D1=>mdout1_1_3, D2=>mdout1_2_3, 
            D3=>mdout1_3_3, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(3));

    mux_67: MUX41
        port map (D0=>mdout1_0_4, D1=>mdout1_1_4, D2=>mdout1_2_4, 
            D3=>mdout1_3_4, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(4));

    mux_66: MUX41
        port map (D0=>mdout1_0_5, D1=>mdout1_1_5, D2=>mdout1_2_5, 
            D3=>mdout1_3_5, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(5));

    mux_65: MUX41
        port map (D0=>mdout1_0_6, D1=>mdout1_1_6, D2=>mdout1_2_6, 
            D3=>mdout1_3_6, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(6));

    mux_64: MUX41
        port map (D0=>mdout1_0_7, D1=>mdout1_1_7, D2=>mdout1_2_7, 
            D3=>mdout1_3_7, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(7));

    mux_63: MUX41
        port map (D0=>mdout1_0_8, D1=>mdout1_1_8, D2=>mdout1_2_8, 
            D3=>mdout1_3_8, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(8));

    mux_62: MUX41
        port map (D0=>mdout1_0_9, D1=>mdout1_1_9, D2=>mdout1_2_9, 
            D3=>mdout1_3_9, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(9));

    mux_61: MUX41
        port map (D0=>mdout1_0_10, D1=>mdout1_1_10, D2=>mdout1_2_10, 
            D3=>mdout1_3_10, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(10));

    mux_60: MUX41
        port map (D0=>mdout1_0_11, D1=>mdout1_1_11, D2=>mdout1_2_11, 
            D3=>mdout1_3_11, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(11));

    mux_59: MUX41
        port map (D0=>mdout1_0_12, D1=>mdout1_1_12, D2=>mdout1_2_12, 
            D3=>mdout1_3_12, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(12));

    mux_58: MUX41
        port map (D0=>mdout1_0_13, D1=>mdout1_1_13, D2=>mdout1_2_13, 
            D3=>mdout1_3_13, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(13));

    mux_57: MUX41
        port map (D0=>mdout1_0_14, D1=>mdout1_1_14, D2=>mdout1_2_14, 
            D3=>mdout1_3_14, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(14));

    mux_56: MUX41
        port map (D0=>mdout1_0_15, D1=>mdout1_1_15, D2=>mdout1_2_15, 
            D3=>mdout1_3_15, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(15));

    mux_55: MUX41
        port map (D0=>mdout1_0_16, D1=>mdout1_1_16, D2=>mdout1_2_16, 
            D3=>mdout1_3_16, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(16));

    mux_54: MUX41
        port map (D0=>mdout1_0_17, D1=>mdout1_1_17, D2=>mdout1_2_17, 
            D3=>mdout1_3_17, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(17));

    mux_53: MUX41
        port map (D0=>mdout1_0_18, D1=>mdout1_1_18, D2=>mdout1_2_18, 
            D3=>mdout1_3_18, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(18));

    mux_52: MUX41
        port map (D0=>mdout1_0_19, D1=>mdout1_1_19, D2=>mdout1_2_19, 
            D3=>mdout1_3_19, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(19));

    mux_51: MUX41
        port map (D0=>mdout1_0_20, D1=>mdout1_1_20, D2=>mdout1_2_20, 
            D3=>mdout1_3_20, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(20));

    mux_50: MUX41
        port map (D0=>mdout1_0_21, D1=>mdout1_1_21, D2=>mdout1_2_21, 
            D3=>mdout1_3_21, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(21));

    mux_49: MUX41
        port map (D0=>mdout1_0_22, D1=>mdout1_1_22, D2=>mdout1_2_22, 
            D3=>mdout1_3_22, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(22));

    mux_48: MUX41
        port map (D0=>mdout1_0_23, D1=>mdout1_1_23, D2=>mdout1_2_23, 
            D3=>mdout1_3_23, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(23));

    mux_47: MUX41
        port map (D0=>mdout1_0_24, D1=>mdout1_1_24, D2=>mdout1_2_24, 
            D3=>mdout1_3_24, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(24));

    mux_46: MUX41
        port map (D0=>mdout1_0_25, D1=>mdout1_1_25, D2=>mdout1_2_25, 
            D3=>mdout1_3_25, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(25));

    mux_45: MUX41
        port map (D0=>mdout1_0_26, D1=>mdout1_1_26, D2=>mdout1_2_26, 
            D3=>mdout1_3_26, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(26));

    mux_44: MUX41
        port map (D0=>mdout1_0_27, D1=>mdout1_1_27, D2=>mdout1_2_27, 
            D3=>mdout1_3_27, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(27));

    mux_43: MUX41
        port map (D0=>mdout1_0_28, D1=>mdout1_1_28, D2=>mdout1_2_28, 
            D3=>mdout1_3_28, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(28));

    mux_42: MUX41
        port map (D0=>mdout1_0_29, D1=>mdout1_1_29, D2=>mdout1_2_29, 
            D3=>mdout1_3_29, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(29));

    mux_41: MUX41
        port map (D0=>mdout1_0_30, D1=>mdout1_1_30, D2=>mdout1_2_30, 
            D3=>mdout1_3_30, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(30));

    mux_40: MUX41
        port map (D0=>mdout1_0_31, D1=>mdout1_1_31, D2=>mdout1_2_31, 
            D3=>mdout1_3_31, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(31));

    mux_39: MUX41
        port map (D0=>mdout1_0_32, D1=>mdout1_1_32, D2=>mdout1_2_32, 
            D3=>mdout1_3_32, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(32));

    mux_38: MUX41
        port map (D0=>mdout1_0_33, D1=>mdout1_1_33, D2=>mdout1_2_33, 
            D3=>mdout1_3_33, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(33));

    mux_37: MUX41
        port map (D0=>mdout1_0_34, D1=>mdout1_1_34, D2=>mdout1_2_34, 
            D3=>mdout1_3_34, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(34));

    mux_36: MUX41
        port map (D0=>mdout1_0_35, D1=>mdout1_1_35, D2=>mdout1_2_35, 
            D3=>mdout1_3_35, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(35));

    mux_35: MUX41
        port map (D0=>mdout1_0_36, D1=>mdout1_1_36, D2=>mdout1_2_36, 
            D3=>mdout1_3_36, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(36));

    mux_34: MUX41
        port map (D0=>mdout1_0_37, D1=>mdout1_1_37, D2=>mdout1_2_37, 
            D3=>mdout1_3_37, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(37));

    mux_33: MUX41
        port map (D0=>mdout1_0_38, D1=>mdout1_1_38, D2=>mdout1_2_38, 
            D3=>mdout1_3_38, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(38));

    mux_32: MUX41
        port map (D0=>mdout1_0_39, D1=>mdout1_1_39, D2=>mdout1_2_39, 
            D3=>mdout1_3_39, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(39));

    mux_31: MUX41
        port map (D0=>mdout1_0_40, D1=>mdout1_1_40, D2=>mdout1_2_40, 
            D3=>mdout1_3_40, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(40));

    mux_30: MUX41
        port map (D0=>mdout1_0_41, D1=>mdout1_1_41, D2=>mdout1_2_41, 
            D3=>mdout1_3_41, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(41));

    mux_29: MUX41
        port map (D0=>mdout1_0_42, D1=>mdout1_1_42, D2=>mdout1_2_42, 
            D3=>mdout1_3_42, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(42));

    mux_28: MUX41
        port map (D0=>mdout1_0_43, D1=>mdout1_1_43, D2=>mdout1_2_43, 
            D3=>mdout1_3_43, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(43));

    mux_27: MUX41
        port map (D0=>mdout1_0_44, D1=>mdout1_1_44, D2=>mdout1_2_44, 
            D3=>mdout1_3_44, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(44));

    mux_26: MUX41
        port map (D0=>mdout1_0_45, D1=>mdout1_1_45, D2=>mdout1_2_45, 
            D3=>mdout1_3_45, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(45));

    mux_25: MUX41
        port map (D0=>mdout1_0_46, D1=>mdout1_1_46, D2=>mdout1_2_46, 
            D3=>mdout1_3_46, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(46));

    mux_24: MUX41
        port map (D0=>mdout1_0_47, D1=>mdout1_1_47, D2=>mdout1_2_47, 
            D3=>mdout1_3_47, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(47));

    mux_23: MUX41
        port map (D0=>mdout1_0_48, D1=>mdout1_1_48, D2=>mdout1_2_48, 
            D3=>mdout1_3_48, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(48));

    mux_22: MUX41
        port map (D0=>mdout1_0_49, D1=>mdout1_1_49, D2=>mdout1_2_49, 
            D3=>mdout1_3_49, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(49));

    mux_21: MUX41
        port map (D0=>mdout1_0_50, D1=>mdout1_1_50, D2=>mdout1_2_50, 
            D3=>mdout1_3_50, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(50));

    mux_20: MUX41
        port map (D0=>mdout1_0_51, D1=>mdout1_1_51, D2=>mdout1_2_51, 
            D3=>mdout1_3_51, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(51));

    mux_19: MUX41
        port map (D0=>mdout1_0_52, D1=>mdout1_1_52, D2=>mdout1_2_52, 
            D3=>mdout1_3_52, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(52));

    mux_18: MUX41
        port map (D0=>mdout1_0_53, D1=>mdout1_1_53, D2=>mdout1_2_53, 
            D3=>mdout1_3_53, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(53));

    mux_17: MUX41
        port map (D0=>mdout1_0_54, D1=>mdout1_1_54, D2=>mdout1_2_54, 
            D3=>mdout1_3_54, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(54));

    mux_16: MUX41
        port map (D0=>mdout1_0_55, D1=>mdout1_1_55, D2=>mdout1_2_55, 
            D3=>mdout1_3_55, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(55));

    mux_15: MUX41
        port map (D0=>mdout1_0_56, D1=>mdout1_1_56, D2=>mdout1_2_56, 
            D3=>mdout1_3_56, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(56));

    mux_14: MUX41
        port map (D0=>mdout1_0_57, D1=>mdout1_1_57, D2=>mdout1_2_57, 
            D3=>mdout1_3_57, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(57));

    mux_13: MUX41
        port map (D0=>mdout1_0_58, D1=>mdout1_1_58, D2=>mdout1_2_58, 
            D3=>mdout1_3_58, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(58));

    mux_12: MUX41
        port map (D0=>mdout1_0_59, D1=>mdout1_1_59, D2=>mdout1_2_59, 
            D3=>mdout1_3_59, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(59));

    mux_11: MUX41
        port map (D0=>mdout1_0_60, D1=>mdout1_1_60, D2=>mdout1_2_60, 
            D3=>mdout1_3_60, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(60));

    mux_10: MUX41
        port map (D0=>mdout1_0_61, D1=>mdout1_1_61, D2=>mdout1_2_61, 
            D3=>mdout1_3_61, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(61));

    mux_9: MUX41
        port map (D0=>mdout1_0_62, D1=>mdout1_1_62, D2=>mdout1_2_62, 
            D3=>mdout1_3_62, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(62));

    mux_8: MUX41
        port map (D0=>mdout1_0_63, D1=>mdout1_1_63, D2=>mdout1_2_63, 
            D3=>mdout1_3_63, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(63));

    mux_7: MUX41
        port map (D0=>mdout1_0_64, D1=>mdout1_1_64, D2=>mdout1_2_64, 
            D3=>mdout1_3_64, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(64));

    mux_6: MUX41
        port map (D0=>mdout1_0_65, D1=>mdout1_1_65, D2=>mdout1_2_65, 
            D3=>mdout1_3_65, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(65));

    mux_5: MUX41
        port map (D0=>mdout1_0_66, D1=>mdout1_1_66, D2=>mdout1_2_66, 
            D3=>mdout1_3_66, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(66));

    mux_4: MUX41
        port map (D0=>mdout1_0_67, D1=>mdout1_1_67, D2=>mdout1_2_67, 
            D3=>mdout1_3_67, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(67));

    mux_3: MUX41
        port map (D0=>mdout1_0_68, D1=>mdout1_1_68, D2=>mdout1_2_68, 
            D3=>mdout1_3_68, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(68));

    mux_2: MUX41
        port map (D0=>mdout1_0_69, D1=>mdout1_1_69, D2=>mdout1_2_69, 
            D3=>mdout1_3_69, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(69));

    mux_1: MUX41
        port map (D0=>mdout1_0_70, D1=>mdout1_1_70, D2=>mdout1_2_70, 
            D3=>mdout1_3_70, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(70));

    mux_0: MUX41
        port map (D0=>mdout1_0_71, D1=>mdout1_1_71, D2=>mdout1_2_71, 
            D3=>mdout1_3_71, SD1=>rptr_9_ff, SD2=>rptr_10_ff, Z=>Q(71));

    empty_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            CI=>scuba_vlo, COUT=>cmp_ci, S0=>open, S1=>open);

    empty_cmp_0: AGEB2
        port map (A0=>rcount_0, A1=>rcount_1, B0=>wcount_r2, 
            B1=>wcount_r3, CI=>cmp_ci, GE=>co0_2);

    empty_cmp_1: AGEB2
        port map (A0=>rcount_2, A1=>rcount_3, B0=>wcount_r4, 
            B1=>wcount_r5, CI=>co0_2, GE=>co1_2);

    empty_cmp_2: AGEB2
        port map (A0=>rcount_4, A1=>rcount_5, B0=>wcount_r6, 
            B1=>wcount_r7, CI=>co1_2, GE=>co2_2);

    empty_cmp_3: AGEB2
        port map (A0=>rcount_6, A1=>rcount_7, B0=>wcount_r8, 
            B1=>wcount_r9, CI=>co2_2, GE=>co3_2);

    empty_cmp_4: AGEB2
        port map (A0=>rcount_8, A1=>rcount_9, B0=>w_g2b_xor_cluster_0, 
            B1=>wcount_r11, CI=>co3_2, GE=>co4_2);

    empty_cmp_5: AGEB2
        port map (A0=>rcount_10, A1=>empty_cmp_set, B0=>wcount_r12, 
            B1=>empty_cmp_clr, CI=>co4_2, GE=>empty_d_c);

    a0: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>empty_d_c, COUT=>open, S0=>empty_d, 
            S1=>open);

    full_cmp_ci_a: FADD2B
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            CI=>scuba_vlo, COUT=>cmp_ci_1, S0=>open, S1=>open);

    full_cmp_0: AGEB2
        port map (A0=>wcount_0, A1=>wcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>cmp_ci_1, GE=>co0_3);

    full_cmp_1: AGEB2
        port map (A0=>wcount_2, A1=>wcount_3, B0=>rcount_w0, 
            B1=>rcount_w1, CI=>co0_3, GE=>co1_3);

    full_cmp_2: AGEB2
        port map (A0=>wcount_4, A1=>wcount_5, B0=>rcount_w2, 
            B1=>rcount_w3, CI=>co1_3, GE=>co2_3);

    full_cmp_3: AGEB2
        port map (A0=>wcount_6, A1=>wcount_7, B0=>rcount_w4, 
            B1=>rcount_w5, CI=>co2_3, GE=>co3_3);

    full_cmp_4: AGEB2
        port map (A0=>wcount_8, A1=>wcount_9, B0=>rcount_w6, 
            B1=>rcount_w7, CI=>co3_3, GE=>co4_3);

    full_cmp_5: AGEB2
        port map (A0=>wcount_10, A1=>wcount_11, B0=>r_g2b_xor_cluster_0, 
            B1=>rcount_w9, CI=>co4_3, GE=>co5_2);

    full_cmp_6: AGEB2
        port map (A0=>wcount_12, A1=>full_cmp_set, B0=>rcount_w10, 
            B1=>full_cmp_clr, CI=>co5_2, GE=>full_d_c);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    a1: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>full_d_c, COUT=>open, S0=>full_d, 
            S1=>open);

    Empty <= empty_i;
    Full <= full_i;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of fifo_16kx16x64 is
    for Structure
        for all:AGEB2 use entity ecp3.AGEB2(V); end for;
        for all:AND2 use entity ecp3.AND2(V); end for;
        for all:CU2 use entity ecp3.CU2(V); end for;
        for all:FADD2B use entity ecp3.FADD2B(V); end for;
        for all:FD1P3BX use entity ecp3.FD1P3BX(V); end for;
        for all:FD1P3DX use entity ecp3.FD1P3DX(V); end for;
        for all:FD1S3BX use entity ecp3.FD1S3BX(V); end for;
        for all:FD1S3DX use entity ecp3.FD1S3DX(V); end for;
        for all:INV use entity ecp3.INV(V); end for;
        for all:MUX41 use entity ecp3.MUX41(V); end for;
        for all:OR2 use entity ecp3.OR2(V); end for;
        for all:ROM16X1A use entity ecp3.ROM16X1A(V); end for;
        for all:VHI use entity ecp3.VHI(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
        for all:XOR2 use entity ecp3.XOR2(V); end for;
        for all:DP16KC use entity ecp3.DP16KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
